# Generated by Django 4.0.6 on 2022-09-12 16:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itle', models.CharField(max_length=200)),
                ('blog_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog_image', models.ImageField(upload_to='blog_app/images/')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
