# Generated by Django 4.0.6 on 2022-09-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_item',
            old_name='itle',
            new_name='title',
        ),
    ]
