# Generated by Django 4.0.6 on 2022-09-12 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_item_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_item',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
