# Generated by Django 4.0.6 on 2022-09-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('blog_content', models.TextField(max_length=2000)),
                ('blog_image', models.ImageField(upload_to='blog_app/images/')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
